version: '3'
services:
  postgres:
    build:
      dockerfile: ./database/Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=home-management
      - POSTGRES_PASSWORD=home-management
